GET http://localhost:3000/cats
###

GET http://localhost:3000/cats/36b8f84d-df4e-4d49-b662-bcde71a8764f

###

POST http://localhost:3000/cats
Content-Type: application/json

{
    "name": "Cat 1",
    "age": 1,
    "breed": "Breed 1"
}
###

POST http://localhost:3000/cats
Content-Type: application/json

{
    "name": "Cat 2",
    "age": 2
}

###
DELETE http://localhost:3000/cats/1

###
GET http://localhost:3000/admin
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "testando jwt",
    "age": 100,
    "email": "myemail@email.com",
    "password": "123456"
}
###
GET http://localhost:3000/users
###
DELETE http://localhost:3000/users/3202f141-e0eb-4356-ad22-2561c8ad3e79
###
POST http://localhost:3000/
