GET http://localhost:3000/cats
###

GET http://localhost:3000/cats/1

###

POST http://localhost:3000/cats
Content-Type: application/json

{
    "name": "Cat 1",
    "age": 1,
    "breed": "Breed 1"
}

###
DELETE http://localhost:3000/cats/1

###
GET http://localhost:3000/admin