GET http://localhost:3000/cats
###

GET http://localhost:3000/cats/36b8f84d-df4e-4d49-b662-bcde71a8764f

###

POST http://localhost:3000/cats
Content-Type: application/json

{
    "name": "Cat 1",
    "age": 1,
    "breed": "Breed 1"
}
###

POST http://localhost:3000/cats
Content-Type: application/json

{
    "name": "Cat 2",
    "age": 2
}

###
DELETE http://localhost:3000/cats/1

###
GET http://localhost:3000/admin
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "olasdfasd",
    "age": 100,
    "email": "myemail@email.com",
    "password": "sadfa"
}
###
GET http://localhost:3000/users
###
DELETE http://localhost:3000/users/3202f141-e0eb-4356-ad22-2561c8ad3e79
###
POST http://localhost:3000/auth
Content-Type: application/json

{
    "id": "6269a3a2-e8ec-499a-baa3-6e210849eaad",
    "pwd": "123456"
}
###
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjY5YTNhMi1lOGVjLTQ5OWEtYmFhMy02ZTIxMDg0OWVhYWQiLCJ1c2VybmFtZSI6InRlc3RhbmRvIGp3dCIsImlhdCI6MTc0MTM3Mzg1OSwiZXhwIjoxNzQxMzczOTE5fQ.Ovl0sE0xIMj7g0S4XC-qiA1T8rl0j-CDtVG3fcPN8uw
